name: Test Windows (Reusable)

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'The runner to use for the jobs (e.g., windows-latest)'
        required: false
        type: string
        default: 'windows-latest'
      dotnet-version:
        description: 'The .NET version to install'
        required: false
        type: string
        default: '9.0.x'

permissions:
  contents: read
  actions: read

jobs:
  test-unit:
    name: Unit Tests - Windows
    runs-on: ${{ inputs.runs-on }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test --configuration Release --no-build --filter "Category=Unit" --logger "trx;LogFileName=windows-unit.trx" --results-directory ./TestResults

    - name: Upload Unit Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-unit-windows
        path: TestResults/*.trx

  test-integration:
    name: Integration Tests - Windows Core Audio
    runs-on: ${{ inputs.runs-on }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Windows Integration Tests
      run: dotnet test --configuration Release --no-build --filter "Category=Integration&Category=Windows" --logger "trx;LogFileName=windows-integration.trx" --results-directory ./TestResults
      shell: pwsh
      continue-on-error: true

    - name: Upload Integration Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-integration-windows
        path: TestResults/*.trx

  test-factory:
    name: Factory Tests - Windows
    runs-on: ${{ inputs.runs-on }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Factory Tests
      run: dotnet test --configuration Release --no-build --filter "FullyQualifiedName~VolumeSubsystemFactoryTests" --logger "trx;LogFileName=windows-factory.trx" --results-directory ./TestResults
      shell: pwsh

    - name: Upload Factory Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-factory-windows
        path: TestResults/*.trx

  test-com-interop:
    name: COM Interop Tests - Windows
    runs-on: ${{ inputs.runs-on }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Specific Windows Tests
      run: dotnet test --configuration Release --no-build --filter "FullyQualifiedName~WindowsVolumeSubsystem" --logger "trx;LogFileName=windows-com-interop.trx" --results-directory ./TestResults
      shell: pwsh
      continue-on-error: true

    - name: Upload COM Interop Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-com-interop-windows
        path: TestResults/*.trx

  test-sample:
    name: Sample App Test - Windows
    runs-on: ${{ inputs.runs-on }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Build Sample App
      run: dotnet build --configuration Release
      working-directory: samples/
      shell: pwsh

    - name: Test Sample App
      shell: pwsh
      working-directory: samples/
      continue-on-error: true
      run: |
        $job = Start-Job -ScriptBlock { dotnet run --configuration Release --no-build }
        if (Wait-Job $job -Timeout 30) { Receive-Job $job }
        else { Stop-Job $job; Write-Host "Sample app test timed out" }
        Remove-Job $job

  summary:
    name: Windows Test Summary
    runs-on: ubuntu-latest
    if: always()
    needs: [test-unit, test-integration, test-factory, test-com-interop, test-sample]
    
    steps:
    - name: Download all test results
      uses: actions/download-artifact@v4
      with:
        path: test-results

    - name: Check for failures
      run: |
        echo "### Windows Test Results Summary" >> $GITHUB_STEP_SUMMARY
        if grep -r -l "outcome=\"Failed\"" test-results; then
          echo "🔴 Some Windows tests failed. Check the artifacts for details." >> $GITHUB_STEP_SUMMARY
          exit 1
        else
          echo "✅ All Windows tests passed!" >> $GITHUB_STEP_SUMMARY
        fi